export enum ProfileTypes {
  PROFILE_DATA = 'PROFILE_DATA',
  PROFILE_FETCH_DATA = 'PROFILE_FETCH_DATA',
  PROFILE_LOADING_STATUS = 'PROFILE_LOADING_STATUS',
  PROFILE_REQUEST_FAILED = 'PROFILE_REQUEST_FAILED',
}
