export enum UserTypes {
  USER_LOGIN = 'USER_LOGIN',
  USER_SIGIN = 'USER_SIGNIN',
  USER_FETCH_LOGIN = 'USER_FETCH_LOGIN',
  USER_FETCH_SIGNIN = 'USER_FETCH_SIGNIN',
  USER_LOADING_STATUS = 'USER_LOADING_STATUS',
  USER_REQUEST_FAILED = 'USER_REQUEST_FAILED',
}
