export enum UserTypes {
  USER_LOGIN = 'USER_LOGIN',
  USER_SIGN = 'USER_SIGN',
  USER_FETCH_LOGIN = 'USER_FETCH_LOGIN',
  USER_FETCH_SIGN = 'USER_FETCH_SIGN',
  USER_LOADING_STATUS = 'USER_LOADING_STATUS',
  USER_REQUEST_FAILED = 'USER_REQUEST_FAILED',
}
