export enum PostTypes {
  CREATE = 'POST_CREATE',
  POST_CREATE_LOADING_STATUS = 'POST_CREATE_LOADING_STATUS',
  POST_CREATE_SET_SUCCESSFUL = 'POST_CREATE_SET_SUCCESSFUL',
  POST_GET_ACTION = 'POST_GET_ACTION',
  POST_SET_COLLECTION = 'POST_SET_COLLECTION',
  // CREATED = 'CREATED',
}
