export enum PostTypes {
  CREATE = 'POST_CREATE',
  POST_CREATE_LOADING_STATUS = 'POST_CREATE_LOADING_STATUS',
  POST_CREATE_SET_SUCCESSFUL = 'POST_CREATE_SET_SUCCESSFUL',
  // CREATED = 'CREATED',
}
